Desktop/Rocket_Elevators_Foundation_2/config/routes.rb
Rails.application.routes.draw do
  resources :interventions
  resources :address_geocodes
  resources :leads
  resources :elevators
  resources :columns
  resources :batteries
  resources :customers
  resources :addresses
  resources :building_details
  resources :buildings
  resources :quotes
	root "rocket#index"
  
	post "/home/testpost", to: "home#testpost"
	get "/index", to: "rocket#index"
	get "/quote", to: "rocket#quote"
	get "/residential", to: "rocket#residential"
	get "/commercial", to: "rocket#commercial"

	mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
	resources :employees
	get 'home/index'
	get 'home_controller/index'
	devise_for :users     

	post "/quotes/create", to: "quotes#create"

	post "/leads/create", to: "leads#create"

	post "/admin/intervention.html.erb", to: "interventions#create"

	get "/watson/refreshaudio", to: "watson#refreshaudio"

	get '/get_building_by_customer/:customer_id', to: 'customers#get_buildings_by_customers'  

	get '/get_battery_by_building/:building_id', to: 'buildings#get_batteries_by_buildings' 

	get '/get_column_by_battery/:battery_id', to: 'batteries#get_columns_by_batteries'  

	get '/get_elevator_by_column/:column_id', to: 'columns#get_elevators_by_columns'
end

Desktop/Rocket_Elevators_Foundation_2/app/models/battery.rb
class Battery < ApplicationRecord
    belongs_to :building
    belongs_to :employee
    has_many :columns
end

Desktop/Rocket_Elevators_Foundation_2/app/controllers/batteries_controller.rb
class BatteriesController < ApplicationController
  before_action :set_battery, only: %i[ show edit update destroy ]

  # GET /batteries or /batteries.json
  def index
    @batteries = Battery.all
  end

  # GET /batteries/1 or /batteries/1.json
  def show
  end

  # GET /batteries/new
  def new
    @battery = Battery.new
  end

  # GET /batteries/1/edit
  def edit
  end

  # POST /batteries or /batteries.json
  def create
    @battery = Battery.new(battery_params)

    respond_to do |format|
      if @battery.save
        format.html { redirect_to @battery, notice: "Battery was successfully created." }
        format.json { render :show, status: :created, location: @battery }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @battery.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /batteries/1 or /batteries/1.json
  def update
    respond_to do |format|
      if @battery.update(battery_params)
        format.html { redirect_to @battery, notice: "Battery was successfully updated." }
        format.json { render :show, status: :ok, location: @battery }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @battery.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /batteries/1 or /batteries/1.json
  def destroy
    @battery.destroy
    respond_to do |format|
      format.html { redirect_to batteries_url, notice: "Battery was successfully destroyed." }
      format.json { head :no_content }
    end
  end
  def get_columns_by_batteries
    @column = Column.where("battery_id = ?", params[:battery_id])
    respond_to do |format|
      format.json { render :json => @column }
    end
  end 

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_battery
      @battery = Battery.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def battery_params
      params.require(:battery).permit(:BType, :DateOfCommissioning, :DateOfLastInspection, :CertificateOfOperations, :Info, :Notes)
    end
end

Desktop/Rocket_Elevators_Foundation_2/app/helpers/batteries_helper.rb
module BatteriesHelper
end

Desktop/Rocket_Elevators_Foundation_2/app/views/batteries/_form.html.erb
<%= form_with(model: battery, local: true) do |form| %>
  <% if battery.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(battery.errors.count, "error") %> prohibited this battery from being saved:</h2>

      <ul>
      <% battery.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :BType %>
    <%= form.text_field :BType %>
  </div>

  <div class="field">
    <%= form.label :DateOfCommissioning %>
    <%= form.date_select :DateOfCommissioning %>
  </div>

  <div class="field">
    <%= form.label :DateOfLastInspection %>
    <%= form.date_select :DateOfLastInspection %>
  </div>

  <div class="field">
    <%= form.label :CertificateOfOperations %>
    <%= form.text_field :CertificateOfOperations %>
  </div>

  <div class="field">
    <%= form.label :Info %>
    <%= form.text_area :Info %>
  </div>

  <div class="field">
    <%= form.label :Notes %>
    <%= form.text_area :Notes %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

Desktop/Rocket_Elevators_Foundation_2/app/views/batteries/edit.html.erb
<h1>Editing Battery</h1>

<%= render 'form', battery: @battery %>

<%= link_to 'Show', @battery %> |
<%= link_to 'Back', batteries_path %>

Desktop/Rocket_Elevators_Foundation_2/app/views/batteries/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Batteries</h1>

<table>
  <thead>
    <tr>
      <th>Btype</th>
      <th>Dateofcommissioning</th>
      <th>Dateoflastinspection</th>
      <th>Certificateofoperations</th>
      <th>Info</th>
      <th>Notes</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @batteries.each do |battery| %>
      <tr>
        <td><%= battery.BType %></td>
        <td><%= battery.DateOfCommissioning %></td>
        <td><%= battery.DateOfLastInspection %></td>
        <td><%= battery.CertificateOfOperations %></td>
        <td><%= battery.Info %></td>
        <td><%= battery.Notes %></td>
        <td><%= link_to 'Show', battery %></td>
        <td><%= link_to 'Edit', edit_battery_path(battery) %></td>
        <td><%= link_to 'Destroy', battery, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Battery', new_battery_path %>

Desktop/Rocket_Elevators_Foundation_2/app/views/batteries/new.html.erb
<h1>New Battery</h1>

<%= render 'form', battery: @battery %>

<%= link_to 'Back', batteries_path %>

Desktop/Rocket_Elevators_Foundation_2/app/views/batteries/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Btype:</strong>
  <%= @battery.BType %>
</p>

<p>
  <strong>Dateofcommissioning:</strong>
  <%= @battery.DateOfCommissioning %>
</p>

<p>
  <strong>Dateoflastinspection:</strong>
  <%= @battery.DateOfLastInspection %>
</p>

<p>
  <strong>Certificateofoperations:</strong>
  <%= @battery.CertificateOfOperations %>
</p>

<p>
  <strong>Info:</strong>
  <%= @battery.Info %>
</p>

<p>
  <strong>Notes:</strong>
  <%= @battery.Notes %>
</p>

<%= link_to 'Edit', edit_battery_path(@battery) %> |
<%= link_to 'Back', batteries_path %>