Desktop/Rocket_Elevators_Foundation_2/config/routes.rb
Rails.application.routes.draw do
  resources :interventions
  resources :address_geocodes
  resources :leads
  resources :elevators
  resources :columns
  resources :batteries
  resources :customers
  resources :addresses
  resources :building_details
  resources :buildings
  resources :quotes
	root "rocket#index"
  
	post "/home/testpost", to: "home#testpost"
	get "/index", to: "rocket#index"
	get "/quote", to: "rocket#quote"
	get "/residential", to: "rocket#residential"
	get "/commercial", to: "rocket#commercial"

	mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
	resources :employees
	get 'home/index'
	get 'home_controller/index'
	devise_for :users     

	post "/quotes/create", to: "quotes#create"

	post "/leads/create", to: "leads#create"

	post "/admin/intervention.html.erb", to: "interventions#create"

	get "/watson/refreshaudio", to: "watson#refreshaudio"

	get '/get_building_by_customer/:customer_id', to: 'customers#get_buildings_by_customers'  

	get '/get_battery_by_building/:building_id', to: 'buildings#get_batteries_by_buildings' 

	get '/get_column_by_battery/:battery_id', to: 'batteries#get_columns_by_batteries'  

	get '/get_elevator_by_column/:column_id', to: 'columns#get_elevators_by_columns'
end

Desktop/Rocket_Elevators_Foundation_2/app/controllers/addresses_controller.rb
class AddressesController < ApplicationController
  before_action :set_address, only: %i[ show edit update destroy ]

  # GET /addresses or /addresses.json
  def index
    @addresses = Address.all
  end

  # GET /addresses/1 or /addresses/1.json
  def show
  end

  # GET /addresses/new
  def new
    @address = Address.new
  end

  # GET /addresses/1/edit
  def edit
  end

  # POST /addresses or /addresses.json
  def create
    @address = Address.new(address_params)

    respond_to do |format|
      if @address.save
        format.html { redirect_to @address, notice: "Address was successfully created." }
        format.json { render :show, status: :created, location: @address }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @address.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /addresses/1 or /addresses/1.json
  def update
    respond_to do |format|
      if @address.update(address_params)
        format.html { redirect_to @address, notice: "Address was successfully updated." }
        format.json { render :show, status: :ok, location: @address }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @address.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /addresses/1 or /addresses/1.json
  def destroy
    @address.destroy
    respond_to do |format|
      format.html { redirect_to addresses_url, notice: "Address was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_address
      @address = Address.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def address_params
      params.require(:address).permit(:TypeOfAddress, :Status, :Entity, :NumberAndStreet, :Apt, :City, :PostalCode, :Country, :Notes)
    end
end

Desktop/Rocket_Elevators_Foundation_2/app/helpers/addresses_helper.rb
module AddressesHelper
end

Desktop/Rocket_Elevators_Foundation_2/app/views/addresses/_form.html.erb
<%= form_with(model: address, local: true) do |form| %>
  <% if address.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(address.errors.count, "error") %> prohibited this address from being saved:</h2>

      <ul>
      <% address.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :TypeOfAddress %>
    <%= form.text_field :TypeOfAddress %>
  </div>

  <div class="field">
    <%= form.label :Status %>
    <%= form.text_field :Status %>
  </div>

  <div class="field">
    <%= form.label :Entity %>
    <%= form.text_field :Entity %>
  </div>

  <div class="field">
    <%= form.label :NumberAndStreet %>
    <%= form.text_field :NumberAndStreet %>
  </div>

  <div class="field">
    <%= form.label :Apt %>
    <%= form.text_field :Apt %>
  </div>

  <div class="field">
    <%= form.label :City %>
    <%= form.text_field :City %>
  </div>

  <div class="field">
    <%= form.label :PostalCode %>
    <%= form.text_field :PostalCode %>
  </div>

  <div class="field">
    <%= form.label :Country %>
    <%= form.text_field :Country %>
  </div>

  <div class="field">
    <%= form.label :Notes %>
    <%= form.text_area :Notes %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

Desktop/Rocket_Elevators_Foundation_2/app/views/addresses/edit.html.erb
<h1>Editing Address</h1>

<%= render 'form', address: @address %>

<%= link_to 'Show', @address %> |
<%= link_to 'Back', addresses_path %>

Desktop/Rocket_Elevators_Foundation_2/app/views/addresses/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Addresses</h1>

<table>
  <thead>
    <tr>
      <th>Typeofaddress</th>
      <th>Status</th>
      <th>Entity</th>
      <th>Numberandstreet</th>
      <th>Apt</th>
      <th>City</th>
      <th>Postalcode</th>
      <th>Country</th>
      <th>Notes</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @addresses.each do |address| %>
      <tr>
        <td><%= address.TypeOfAddress %></td>
        <td><%= address.Status %></td>
        <td><%= address.Entity %></td>
        <td><%= address.NumberAndStreet %></td>
        <td><%= address.Apt %></td>
        <td><%= address.City %></td>
        <td><%= address.PostalCode %></td>
        <td><%= address.Country %></td>
        <td><%= address.Notes %></td>
        <td><%= link_to 'Show', address %></td>
        <td><%= link_to 'Edit', edit_address_path(address) %></td>
        <td><%= link_to 'Destroy', address, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Address', new_address_path %>

Desktop/Rocket_Elevators_Foundation_2/app/views/addresses/new.html.erb
<h1>New Address</h1>

<%= render 'form', address: @address %>

<%= link_to 'Back', addresses_path %>

Desktop/Rocket_Elevators_Foundation_2/app/views/addresses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Typeofaddress:</strong>
  <%= @address.TypeOfAddress %>
</p>

<p>
  <strong>Status:</strong>
  <%= @address.Status %>
</p>

<p>
  <strong>Entity:</strong>
  <%= @address.Entity %>
</p>

<p>
  <strong>Numberandstreet:</strong>
  <%= @address.NumberAndStreet %>
</p>

<p>
  <strong>Apt:</strong>
  <%= @address.Apt %>
</p>

<p>
  <strong>City:</strong>
  <%= @address.City %>
</p>

<p>
  <strong>Postalcode:</strong>
  <%= @address.PostalCode %>
</p>

<p>
  <strong>Country:</strong>
  <%= @address.Country %>
</p>

<p>
  <strong>Notes:</strong>
  <%= @address.Notes %>
</p>

<%= link_to 'Edit', edit_address_path(@address) %> |
<%= link_to 'Back', addresses_path %>